MODEL:
  BACKBONE:
    NAME: bninception
  PRETRAIN: output-bninception-cub/model_005000.pth

SAVE_DIR: output-bninception-cub

SOLVER:
  MAX_ITERS: 5000
  STEPS: [1200]
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.00003
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0005

DATA:
  TRAIN_IMG_SOURCE: resource/datasets/CUB_200_2011/train.txt
  TEST_IMG_SOURCE: resource/datasets/CUB_200_2011/test.txt
  TRAIN_BATCHSIZE: 200
  TEST_BATCHSIZE: 128
  NUM_WORKERS: 8
  NUM_INSTANCES: 5

VALIDATION:
  VERBOSE: 200
